parameters:
#    music_manager_manage.example.class: MusicManager\ManageBundle\Example

services:
#    music_manager_manage.example:
#        class: %music_manager_manage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
